# Dependencies
theme: jekyll-theme-cayman

# Providing atom.xml
plugins:
  - jekyll-sitemap
  - jekyll-feed

feed:
  path: atom.xml

# Social
title: MuleSoft user group
description: "MuleSoft user group"
author: "Jeroen Desloovere"

# Marketing
tag_manager: GTM-KJG6LVQ5

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css:              "https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
  css_hash:         "sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
  bootstrap:        "https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
  bootstrap_hash:   "sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
  jquery:           "https://code.jquery.com/jquery-3.3.1.slim.min.js"
  jquery_hash:      "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
  popper:           "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
  popper_hash:      "sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
